### ISSUE TITLE
ChannelCount might be zero (0) with 1 CPU

### ISSUE THREAD

**Issue by cc-cpo** [microstream-one/bookstore-demo#1]
Hello,

I am setting up microstream using Spring and found this snippet:
`configuration.setChannelCount(Integer.highestOneBit(Runtime.getRuntime().availableProcessors() - 1));`
in https://github.com/microstream-one/bookstore-demo/blob/master/src/main/java/one/microstream/demo/bookstore/BookStoreDemo.java#L185

Yet I wonder how this works with only 1 CPU core

**I would expect** the channelCount to be set to "1" if I have only 1 CPU core

**What happens** is that  channelCount is set to **"0"**

Thanks for clarifying.

Stefan

**Comment by fh-ms** [comment]
Thanks for the hint, this is indeed wrong for only 1 core.
Corrected channel calculation to use min 1 channel.
