### ISSUE TITLE
why the microstream write performance is not good as DB? microsteam write cost is about 100ms+

### ISSUE THREAD

**Issue by useryq8** [microstream-one/bookstore-demo#10]
I just fork the bookstore-demo and add an api to add boot(call the microstream store), I only add the log but find that it is very slow when adding one boot. you can my project https://github.com/yqbjtu/bookstore-demo/tree/feat/write_perf_log, use the feat/write_perf_log branch, https://github.com/yqbjtu/bookstore-demo/blob/feat/write_perf_log/perf-log/perf-log.md.  I used the ssd and  my machine has 32G main memory,  Java jdk-17.0.4

@mstahv 

Should I change the store way?  I just copied the bookstore-demo project,  or microstream is designed mainly used for reading  such as the read/write is 9:1,

**Comment by mstahv** [comment]
@fh-ms is the best expert on earth to comment if that is a lot or not

**Comment by useryq8** [comment]
> The reason of the poor performance ist that the books are added and stored one by one.
> 
> If you add them in batch and store the changes once, it goes down to a few milliseconds.
> 
> I put the changes in a PR: [yqbjtu#1](https://github.com/yqbjtu/bookstore-demo/pull/1)

Thanks your reply!

**Comment by useryq8** [comment]
> The reason of the poor performance ist that the books are added and stored one by one.
> 
> If you add them in batch and store the changes once, it goes down to a few milliseconds.
> 
> I put the changes in a PR: [yqbjtu#1](https://github.com/yqbjtu/bookstore-demo/pull/1)

 Thanks your reply!   @fh-ms 

But I can't use the batch mode. In my application, some users add books(it is other entity, I use book as example) , after they add, It is necessary to save the add books, it is like one user adds one book , but there are many adding.  If  I use batch mode (such as every 5 minutes to save once),  after userA add bookA1, it can't find bookA1 immediately for the finding from the microstream storage.  when the machine or application shutdowns accidently, the data will be lost for it save data every 5 minutes.

my application throughtput is small, about 60 books will be added every seconds, the totla count will 5000 million bookes. but the data needs to be saved integrally and can't be lost.  after a book is added. other pipelin will queried this books immediately, so the batch mode can't be used.

Do we have any setting to promote the writing performance as DB? the read performace is better the DB(we already veried this point), but our application needs to write data immediately when it is added

**Comment by useryq8** [comment]
Could we give the detail microstream write performance comparing with DB,   such as in the when there are 10 million books, when adding on book once ,the write cost time is xxx in microstream.   @fh-ms @hg-ms   

from the bookstore-demo, the microstream write performance  is not good as DB,  We need this metric to decide which apps are suitable to use microstream.  Thank you very much!

every framework has its own suitable use scenario。 microstream reading is very fast.

**Comment by fh-ms** [comment]
This demo is optimized for read operations. If you want to achieve a high write throughput, you can either segment your data or use lazy collections. See details [here](https://github.com/eclipse-store/store/discussions/111#discussioncomment-8079997), and results [here](https://github.com/eclipse-store/store/discussions/111#discussioncomment-8081437).
