### ISSUE TITLE
Compile error in ViewEntity

### ISSUE THREAD

**Issue by Antonius-Steinkamp** [microstream-one/bookstore-demo#11]
![image](https://github.com/microstream-one/bookstore-demo/assets/16778138/8337336d-eb51-4c8b-997f-0c49fd88b817)

**Comment by Antonius-Steinkamp** [comment]
![image](https://github.com/microstream-one/bookstore-demo/assets/16778138/3c45b92a-f09a-4065-a615-3dc6f85eee29)

**Comment by fh-ms** [comment]
By default, assigning a value back to a lambda variable is valid syntax. I guess the reason is a different compiler setting in your IDE.
